### ISSUE TITLE
Adjacent rooms bug

### ISSUE THREAD

**Issue by asimard1** [syyePhenomenol/RandoMapMod#1]
Sometimes, some rooms are shown in teal when they are not actually adjacent. For example, the room selected here (Fungus3_24) is shown as adjacent to King's Pass but in the top we can see that it's actually 11 transitions away.
![image](https://user-images.githubusercontent.com/58919185/187101594-71c6cd6a-20e0-4af4-9271-b9dd7cf383d1.png)

(Here's the proof that it shows as adjacent.)
![image](https://user-images.githubusercontent.com/58919185/187101636-d0af8f18-3513-4a23-acd2-ad0425ac3dce.png)

Here is my modlog (not much information from what I can tell...), is there any other file that would have pertinent info?
[ModLog.txt](https://github.com/syyePhenomenol/RandoMapMod/files/9440770/ModLog.txt)

**Comment by syyePhenomenol** [comment]
I've found the bug, it'll be fixed in the next update

**Comment by asimard1** [comment]
Current room still isn't displayed correctly sometimes (first time in a 2h session).
![image](https://user-images.githubusercontent.com/58919185/187323121-c403a49f-99ab-4565-8386-87f82ed4d6b6.png)
![image](https://user-images.githubusercontent.com/58919185/187323164-be7bdae0-84ab-4879-af67-6eceed0cd36f.png)

**Comment by asimard1** [comment]
Also, in this case it shows the color correctly, but I still have unchecked transitions and the room isn't brighter...

![image](https://user-images.githubusercontent.com/58919185/187323412-6462e914-91d4-42a3-b940-035156723857.png)

**Comment by asimard1** [comment]
Actually, none of the rooms show up as bright at all... I'll try restarting the game, here's the modlog.
[ModLog.txt](https://github.com/syyePhenomenol/RandoMapMod/files/9448706/ModLog.txt)

**Comment by syyePhenomenol** [comment]
I've identified the bug that is causing your current problems. I'm working on it
